name: pysodes

channels:
  - conda-forge

dependencies:

  # C++
  - cmake>=3.13, <3.17
  - ninja
  - eigen
  - boost==1.74
  - gxx_linux-64  # [linux]
  - ccache  # [unix]

  # Python
  - pip
  - python >=3.6
  - invoke
  - colorama

  # Conda tools
  - exec-wrappers

environment:

  BUILD_DIR:
    - {{ root }}/build  # [unix]
    - {{ root }}/.build  # [win]