name: pysodes

channels:
  - conda-forge

dependencies:

  # C++
  - cmake>=3.13
  - ninja
  - eigen
  - gxx_linux-64=7.3.0  # [linux]
  - ccache  # [unix]

  # Python
  - pip
  - python >=3.6

  # Conda tools
  - exec-wrappers