name: pysodes

channels:
  - conda-forge

dependencies:

  # C++
  - cmake>=3.13, <3.18
  - ninja
  - eigen
  - boost==1.74
  - gxx_linux-64  # [linux]
  - clangxx_osx-64=9.0.0  # [osx]
  - ccache  # [unix]

  # For the bindings
  - pybind11

  # Python
  - pip
  - python >=3.6, <3.9
  - ipython
  - numpy
  - setuptools
  - invoke
  - colorama
  - scipy
  - matplotlib

  # Python notebooks
  - jupyter
  - jupyter_contrib_nbextensions
  - jupyter_nbextensions_configurator

  # For python tests
  - pytest
  - pytest-runner
  - pytest-regressions
  - pytest-xdist

  # Conda tools
  - exec-wrappers

environment:

  BUILD_DIR:
    - {{ root }}/build-sodes

  PYTHONPATH:
    - {{ root }}/src